version: "3.7"
services:
  db:
    # image: mysql:8.0
    build: ./mysql/
    container_name: mysql8_3sem
    
    environment:
      # MYSQL_DATABASE: 'db'
      # # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'dev'
      # # You can use whatever password you like
      # MYSQL_PASSWORD: 'ax2'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./data:/var/lib/mysql # for data
      - ./scripts:/scripts
      - ./mysql/startscript:/docker-entrypoint-initdb.d
    networks:
      - tomcat_network

  web:
    # image:  tomcat:9.0.37-jdk8
    build: ./tomcat/
    container_name: tomcat_3sem
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    environment:
      CONNECTION_STR: "jdbc:mysql://db:3306/database_name"
      USER: "example_db_user" # database user to use in tomcat apps
      PW: "example_db_pass" # database password
      DEPLOYED: "true"

    # ports:
    #  - "8080:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/setenv.sh:/usr/local/tomcat/bin/setenv.sh
    networks:
      - tomcat_network
    # copy the tomcat manager app and make it accessible outside of localhost (then start tomcat)
    command: sh -c "cp -r /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps/manager && mv /tmp/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml && catalina.sh run"

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx_3sem
    restart: unless-stopped
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      # - ./data/certbot/conf:/etc/letsencrypt
      # - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - tomcat_network

networks:
  tomcat_network:
    driver: bridge